// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greetercenter/greeter.proto

package GreeterCenter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BreakfastRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastRequestMessage) Reset()         { *m = BreakfastRequestMessage{} }
func (m *BreakfastRequestMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastRequestMessage) ProtoMessage()    {}
func (*BreakfastRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e10c60664077d5, []int{0}
}

func (m *BreakfastRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastRequestMessage.Unmarshal(m, b)
}
func (m *BreakfastRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastRequestMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastRequestMessage.Merge(m, src)
}
func (m *BreakfastRequestMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastRequestMessage.Size(m)
}
func (m *BreakfastRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastRequestMessage proto.InternalMessageInfo

func (m *BreakfastRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BreakfastResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastResponseMessage) Reset()         { *m = BreakfastResponseMessage{} }
func (m *BreakfastResponseMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastResponseMessage) ProtoMessage()    {}
func (*BreakfastResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e10c60664077d5, []int{1}
}

func (m *BreakfastResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastResponseMessage.Unmarshal(m, b)
}
func (m *BreakfastResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastResponseMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastResponseMessage.Merge(m, src)
}
func (m *BreakfastResponseMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastResponseMessage.Size(m)
}
func (m *BreakfastResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastResponseMessage proto.InternalMessageInfo

func (m *BreakfastResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BreakfastResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BreakfastResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LunchRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchRequestMessage) Reset()         { *m = LunchRequestMessage{} }
func (m *LunchRequestMessage) String() string { return proto.CompactTextString(m) }
func (*LunchRequestMessage) ProtoMessage()    {}
func (*LunchRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e10c60664077d5, []int{2}
}

func (m *LunchRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchRequestMessage.Unmarshal(m, b)
}
func (m *LunchRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchRequestMessage.Marshal(b, m, deterministic)
}
func (m *LunchRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchRequestMessage.Merge(m, src)
}
func (m *LunchRequestMessage) XXX_Size() int {
	return xxx_messageInfo_LunchRequestMessage.Size(m)
}
func (m *LunchRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchRequestMessage proto.InternalMessageInfo

func (m *LunchRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LunchResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchResponseMessage) Reset()         { *m = LunchResponseMessage{} }
func (m *LunchResponseMessage) String() string { return proto.CompactTextString(m) }
func (*LunchResponseMessage) ProtoMessage()    {}
func (*LunchResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e10c60664077d5, []int{3}
}

func (m *LunchResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchResponseMessage.Unmarshal(m, b)
}
func (m *LunchResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchResponseMessage.Marshal(b, m, deterministic)
}
func (m *LunchResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchResponseMessage.Merge(m, src)
}
func (m *LunchResponseMessage) XXX_Size() int {
	return xxx_messageInfo_LunchResponseMessage.Size(m)
}
func (m *LunchResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchResponseMessage proto.InternalMessageInfo

func (m *LunchResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LunchResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LunchResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DinnerRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerRequestMessage) Reset()         { *m = DinnerRequestMessage{} }
func (m *DinnerRequestMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerRequestMessage) ProtoMessage()    {}
func (*DinnerRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e10c60664077d5, []int{4}
}

func (m *DinnerRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerRequestMessage.Unmarshal(m, b)
}
func (m *DinnerRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerRequestMessage.Marshal(b, m, deterministic)
}
func (m *DinnerRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerRequestMessage.Merge(m, src)
}
func (m *DinnerRequestMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerRequestMessage.Size(m)
}
func (m *DinnerRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerRequestMessage proto.InternalMessageInfo

func (m *DinnerRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DinnerResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerResponseMessage) Reset()         { *m = DinnerResponseMessage{} }
func (m *DinnerResponseMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerResponseMessage) ProtoMessage()    {}
func (*DinnerResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e10c60664077d5, []int{5}
}

func (m *DinnerResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerResponseMessage.Unmarshal(m, b)
}
func (m *DinnerResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerResponseMessage.Marshal(b, m, deterministic)
}
func (m *DinnerResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerResponseMessage.Merge(m, src)
}
func (m *DinnerResponseMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerResponseMessage.Size(m)
}
func (m *DinnerResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerResponseMessage proto.InternalMessageInfo

func (m *DinnerResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DinnerResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DinnerResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*BreakfastRequestMessage)(nil), "GreeterCenter.BreakfastRequestMessage")
	proto.RegisterType((*BreakfastResponseMessage)(nil), "GreeterCenter.BreakfastResponseMessage")
	proto.RegisterType((*LunchRequestMessage)(nil), "GreeterCenter.LunchRequestMessage")
	proto.RegisterType((*LunchResponseMessage)(nil), "GreeterCenter.LunchResponseMessage")
	proto.RegisterType((*DinnerRequestMessage)(nil), "GreeterCenter.DinnerRequestMessage")
	proto.RegisterType((*DinnerResponseMessage)(nil), "GreeterCenter.DinnerResponseMessage")
}

func init() { proto.RegisterFile("greetercenter/greeter.proto", fileDescriptor_32e10c60664077d5) }

var fileDescriptor_32e10c60664077d5 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0x4a, 0x4e, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x87, 0xf2, 0xf4, 0x0a, 0x8a, 0xf2,
	0x4b, 0xf2, 0x85, 0x78, 0xdd, 0x21, 0x5c, 0x67, 0xb0, 0xa4, 0x92, 0x2e, 0x97, 0xb8, 0x53, 0x51,
	0x6a, 0x62, 0x76, 0x5a, 0x62, 0x71, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x6f, 0x6a,
	0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0x14, 0xc2, 0x25, 0x81, 0xa4, 0xbc, 0xb8, 0x20, 0x3f, 0xaf,
	0x38, 0x15, 0xa6, 0x5e, 0x80, 0x8b, 0x39, 0xb7, 0x38, 0x1d, 0xaa, 0x1c, 0xc4, 0x04, 0x99, 0x90,
	0x9c, 0x9f, 0x92, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66, 0x83, 0xc4, 0x52, 0x12,
	0x4b, 0x12, 0x25, 0x98, 0x21, 0xa6, 0x82, 0xd8, 0x4a, 0x9a, 0x5c, 0xc2, 0x3e, 0xa5, 0x79, 0xc9,
	0x19, 0x44, 0x38, 0x20, 0x80, 0x4b, 0x04, 0xaa, 0x94, 0x5a, 0x96, 0x6b, 0x71, 0x89, 0xb8, 0x64,
	0xe6, 0xe5, 0xa5, 0x16, 0x11, 0x61, 0x7b, 0x20, 0x97, 0x28, 0x4c, 0x2d, 0x95, 0xac, 0x37, 0x9a,
	0xc0, 0xc4, 0xc5, 0xec, 0x9a, 0x58, 0x22, 0x14, 0xc7, 0xc5, 0x09, 0x0f, 0x59, 0x21, 0x35, 0x3d,
	0x94, 0x58, 0xd2, 0xc3, 0x11, 0x45, 0x52, 0xea, 0xb8, 0xd5, 0xa1, 0xb8, 0x4f, 0x89, 0x41, 0x28,
	0x88, 0x8b, 0x15, 0x1c, 0x70, 0x42, 0x4a, 0x68, 0x7a, 0xb0, 0x84, 0xbc, 0x94, 0x32, 0x76, 0x35,
	0xe8, 0x66, 0x86, 0x72, 0xb1, 0x41, 0x82, 0x43, 0x08, 0x5d, 0x03, 0xb6, 0x10, 0x95, 0x52, 0xc1,
	0xa1, 0x08, 0xcd, 0xd8, 0x24, 0x36, 0x70, 0x4a, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0xec, 0x9d, 0x09, 0xc8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EatClient is the client API for Eat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EatClient interface {
	Breakfast(ctx context.Context, in *BreakfastRequestMessage, opts ...grpc.CallOption) (*BreakfastResponseMessage, error)
	Lunch(ctx context.Context, in *LunchRequestMessage, opts ...grpc.CallOption) (*LunchResponseMessage, error)
	Dinner(ctx context.Context, in *DinnerRequestMessage, opts ...grpc.CallOption) (*DinnerResponseMessage, error)
}

type eatClient struct {
	cc *grpc.ClientConn
}

func NewEatClient(cc *grpc.ClientConn) EatClient {
	return &eatClient{cc}
}

func (c *eatClient) Breakfast(ctx context.Context, in *BreakfastRequestMessage, opts ...grpc.CallOption) (*BreakfastResponseMessage, error) {
	out := new(BreakfastResponseMessage)
	err := c.cc.Invoke(ctx, "/GreeterCenter.Eat/Breakfast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eatClient) Lunch(ctx context.Context, in *LunchRequestMessage, opts ...grpc.CallOption) (*LunchResponseMessage, error) {
	out := new(LunchResponseMessage)
	err := c.cc.Invoke(ctx, "/GreeterCenter.Eat/Lunch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eatClient) Dinner(ctx context.Context, in *DinnerRequestMessage, opts ...grpc.CallOption) (*DinnerResponseMessage, error) {
	out := new(DinnerResponseMessage)
	err := c.cc.Invoke(ctx, "/GreeterCenter.Eat/Dinner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EatServer is the server API for Eat service.
type EatServer interface {
	Breakfast(context.Context, *BreakfastRequestMessage) (*BreakfastResponseMessage, error)
	Lunch(context.Context, *LunchRequestMessage) (*LunchResponseMessage, error)
	Dinner(context.Context, *DinnerRequestMessage) (*DinnerResponseMessage, error)
}

// UnimplementedEatServer can be embedded to have forward compatible implementations.
type UnimplementedEatServer struct {
}

func (*UnimplementedEatServer) Breakfast(ctx context.Context, req *BreakfastRequestMessage) (*BreakfastResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Breakfast not implemented")
}
func (*UnimplementedEatServer) Lunch(ctx context.Context, req *LunchRequestMessage) (*LunchResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lunch not implemented")
}
func (*UnimplementedEatServer) Dinner(ctx context.Context, req *DinnerRequestMessage) (*DinnerResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dinner not implemented")
}

func RegisterEatServer(s *grpc.Server, srv EatServer) {
	s.RegisterService(&_Eat_serviceDesc, srv)
}

func _Eat_Breakfast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreakfastRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EatServer).Breakfast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreeterCenter.Eat/Breakfast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EatServer).Breakfast(ctx, req.(*BreakfastRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eat_Lunch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LunchRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EatServer).Lunch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreeterCenter.Eat/Lunch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EatServer).Lunch(ctx, req.(*LunchRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eat_Dinner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DinnerRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EatServer).Dinner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreeterCenter.Eat/Dinner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EatServer).Dinner(ctx, req.(*DinnerRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Eat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GreeterCenter.Eat",
	HandlerType: (*EatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Breakfast",
			Handler:    _Eat_Breakfast_Handler,
		},
		{
			MethodName: "Lunch",
			Handler:    _Eat_Lunch_Handler,
		},
		{
			MethodName: "Dinner",
			Handler:    _Eat_Dinner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetercenter/greeter.proto",
}
