// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greetercenter/greetercenter.proto

package greetercenter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BreakfastEatRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastEatRequestMessage) Reset()         { *m = BreakfastEatRequestMessage{} }
func (m *BreakfastEatRequestMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastEatRequestMessage) ProtoMessage()    {}
func (*BreakfastEatRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{0}
}

func (m *BreakfastEatRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastEatRequestMessage.Unmarshal(m, b)
}
func (m *BreakfastEatRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastEatRequestMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastEatRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastEatRequestMessage.Merge(m, src)
}
func (m *BreakfastEatRequestMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastEatRequestMessage.Size(m)
}
func (m *BreakfastEatRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastEatRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastEatRequestMessage proto.InternalMessageInfo

func (m *BreakfastEatRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BreakfastEatResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastEatResponseMessage) Reset()         { *m = BreakfastEatResponseMessage{} }
func (m *BreakfastEatResponseMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastEatResponseMessage) ProtoMessage()    {}
func (*BreakfastEatResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{1}
}

func (m *BreakfastEatResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastEatResponseMessage.Unmarshal(m, b)
}
func (m *BreakfastEatResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastEatResponseMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastEatResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastEatResponseMessage.Merge(m, src)
}
func (m *BreakfastEatResponseMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastEatResponseMessage.Size(m)
}
func (m *BreakfastEatResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastEatResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastEatResponseMessage proto.InternalMessageInfo

func (m *BreakfastEatResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BreakfastEatResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BreakfastEatResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LunchEatRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchEatRequestMessage) Reset()         { *m = LunchEatRequestMessage{} }
func (m *LunchEatRequestMessage) String() string { return proto.CompactTextString(m) }
func (*LunchEatRequestMessage) ProtoMessage()    {}
func (*LunchEatRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{2}
}

func (m *LunchEatRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchEatRequestMessage.Unmarshal(m, b)
}
func (m *LunchEatRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchEatRequestMessage.Marshal(b, m, deterministic)
}
func (m *LunchEatRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchEatRequestMessage.Merge(m, src)
}
func (m *LunchEatRequestMessage) XXX_Size() int {
	return xxx_messageInfo_LunchEatRequestMessage.Size(m)
}
func (m *LunchEatRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchEatRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchEatRequestMessage proto.InternalMessageInfo

func (m *LunchEatRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LunchEatResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchEatResponseMessage) Reset()         { *m = LunchEatResponseMessage{} }
func (m *LunchEatResponseMessage) String() string { return proto.CompactTextString(m) }
func (*LunchEatResponseMessage) ProtoMessage()    {}
func (*LunchEatResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{3}
}

func (m *LunchEatResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchEatResponseMessage.Unmarshal(m, b)
}
func (m *LunchEatResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchEatResponseMessage.Marshal(b, m, deterministic)
}
func (m *LunchEatResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchEatResponseMessage.Merge(m, src)
}
func (m *LunchEatResponseMessage) XXX_Size() int {
	return xxx_messageInfo_LunchEatResponseMessage.Size(m)
}
func (m *LunchEatResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchEatResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchEatResponseMessage proto.InternalMessageInfo

func (m *LunchEatResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LunchEatResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LunchEatResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DinnerEatRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerEatRequestMessage) Reset()         { *m = DinnerEatRequestMessage{} }
func (m *DinnerEatRequestMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerEatRequestMessage) ProtoMessage()    {}
func (*DinnerEatRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{4}
}

func (m *DinnerEatRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerEatRequestMessage.Unmarshal(m, b)
}
func (m *DinnerEatRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerEatRequestMessage.Marshal(b, m, deterministic)
}
func (m *DinnerEatRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerEatRequestMessage.Merge(m, src)
}
func (m *DinnerEatRequestMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerEatRequestMessage.Size(m)
}
func (m *DinnerEatRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerEatRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerEatRequestMessage proto.InternalMessageInfo

func (m *DinnerEatRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DinnerEatResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerEatResponseMessage) Reset()         { *m = DinnerEatResponseMessage{} }
func (m *DinnerEatResponseMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerEatResponseMessage) ProtoMessage()    {}
func (*DinnerEatResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{5}
}

func (m *DinnerEatResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerEatResponseMessage.Unmarshal(m, b)
}
func (m *DinnerEatResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerEatResponseMessage.Marshal(b, m, deterministic)
}
func (m *DinnerEatResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerEatResponseMessage.Merge(m, src)
}
func (m *DinnerEatResponseMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerEatResponseMessage.Size(m)
}
func (m *DinnerEatResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerEatResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerEatResponseMessage proto.InternalMessageInfo

func (m *DinnerEatResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DinnerEatResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DinnerEatResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type BreakfastDrinkRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastDrinkRequestMessage) Reset()         { *m = BreakfastDrinkRequestMessage{} }
func (m *BreakfastDrinkRequestMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastDrinkRequestMessage) ProtoMessage()    {}
func (*BreakfastDrinkRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{6}
}

func (m *BreakfastDrinkRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastDrinkRequestMessage.Unmarshal(m, b)
}
func (m *BreakfastDrinkRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastDrinkRequestMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastDrinkRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastDrinkRequestMessage.Merge(m, src)
}
func (m *BreakfastDrinkRequestMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastDrinkRequestMessage.Size(m)
}
func (m *BreakfastDrinkRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastDrinkRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastDrinkRequestMessage proto.InternalMessageInfo

func (m *BreakfastDrinkRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BreakfastDrinkResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastDrinkResponseMessage) Reset()         { *m = BreakfastDrinkResponseMessage{} }
func (m *BreakfastDrinkResponseMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastDrinkResponseMessage) ProtoMessage()    {}
func (*BreakfastDrinkResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{7}
}

func (m *BreakfastDrinkResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastDrinkResponseMessage.Unmarshal(m, b)
}
func (m *BreakfastDrinkResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastDrinkResponseMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastDrinkResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastDrinkResponseMessage.Merge(m, src)
}
func (m *BreakfastDrinkResponseMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastDrinkResponseMessage.Size(m)
}
func (m *BreakfastDrinkResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastDrinkResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastDrinkResponseMessage proto.InternalMessageInfo

func (m *BreakfastDrinkResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BreakfastDrinkResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BreakfastDrinkResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LunchDrinkRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchDrinkRequestMessage) Reset()         { *m = LunchDrinkRequestMessage{} }
func (m *LunchDrinkRequestMessage) String() string { return proto.CompactTextString(m) }
func (*LunchDrinkRequestMessage) ProtoMessage()    {}
func (*LunchDrinkRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{8}
}

func (m *LunchDrinkRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchDrinkRequestMessage.Unmarshal(m, b)
}
func (m *LunchDrinkRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchDrinkRequestMessage.Marshal(b, m, deterministic)
}
func (m *LunchDrinkRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchDrinkRequestMessage.Merge(m, src)
}
func (m *LunchDrinkRequestMessage) XXX_Size() int {
	return xxx_messageInfo_LunchDrinkRequestMessage.Size(m)
}
func (m *LunchDrinkRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchDrinkRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchDrinkRequestMessage proto.InternalMessageInfo

func (m *LunchDrinkRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LunchDrinkResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchDrinkResponseMessage) Reset()         { *m = LunchDrinkResponseMessage{} }
func (m *LunchDrinkResponseMessage) String() string { return proto.CompactTextString(m) }
func (*LunchDrinkResponseMessage) ProtoMessage()    {}
func (*LunchDrinkResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{9}
}

func (m *LunchDrinkResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchDrinkResponseMessage.Unmarshal(m, b)
}
func (m *LunchDrinkResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchDrinkResponseMessage.Marshal(b, m, deterministic)
}
func (m *LunchDrinkResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchDrinkResponseMessage.Merge(m, src)
}
func (m *LunchDrinkResponseMessage) XXX_Size() int {
	return xxx_messageInfo_LunchDrinkResponseMessage.Size(m)
}
func (m *LunchDrinkResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchDrinkResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchDrinkResponseMessage proto.InternalMessageInfo

func (m *LunchDrinkResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LunchDrinkResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LunchDrinkResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DinnerDrinkRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerDrinkRequestMessage) Reset()         { *m = DinnerDrinkRequestMessage{} }
func (m *DinnerDrinkRequestMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerDrinkRequestMessage) ProtoMessage()    {}
func (*DinnerDrinkRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{10}
}

func (m *DinnerDrinkRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerDrinkRequestMessage.Unmarshal(m, b)
}
func (m *DinnerDrinkRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerDrinkRequestMessage.Marshal(b, m, deterministic)
}
func (m *DinnerDrinkRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerDrinkRequestMessage.Merge(m, src)
}
func (m *DinnerDrinkRequestMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerDrinkRequestMessage.Size(m)
}
func (m *DinnerDrinkRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerDrinkRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerDrinkRequestMessage proto.InternalMessageInfo

func (m *DinnerDrinkRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DinnerDrinkResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerDrinkResponseMessage) Reset()         { *m = DinnerDrinkResponseMessage{} }
func (m *DinnerDrinkResponseMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerDrinkResponseMessage) ProtoMessage()    {}
func (*DinnerDrinkResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{11}
}

func (m *DinnerDrinkResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerDrinkResponseMessage.Unmarshal(m, b)
}
func (m *DinnerDrinkResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerDrinkResponseMessage.Marshal(b, m, deterministic)
}
func (m *DinnerDrinkResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerDrinkResponseMessage.Merge(m, src)
}
func (m *DinnerDrinkResponseMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerDrinkResponseMessage.Size(m)
}
func (m *DinnerDrinkResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerDrinkResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerDrinkResponseMessage proto.InternalMessageInfo

func (m *DinnerDrinkResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DinnerDrinkResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DinnerDrinkResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type BreakfastPlayRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastPlayRequestMessage) Reset()         { *m = BreakfastPlayRequestMessage{} }
func (m *BreakfastPlayRequestMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastPlayRequestMessage) ProtoMessage()    {}
func (*BreakfastPlayRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{12}
}

func (m *BreakfastPlayRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastPlayRequestMessage.Unmarshal(m, b)
}
func (m *BreakfastPlayRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastPlayRequestMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastPlayRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastPlayRequestMessage.Merge(m, src)
}
func (m *BreakfastPlayRequestMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastPlayRequestMessage.Size(m)
}
func (m *BreakfastPlayRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastPlayRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastPlayRequestMessage proto.InternalMessageInfo

func (m *BreakfastPlayRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BreakfastPlayResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakfastPlayResponseMessage) Reset()         { *m = BreakfastPlayResponseMessage{} }
func (m *BreakfastPlayResponseMessage) String() string { return proto.CompactTextString(m) }
func (*BreakfastPlayResponseMessage) ProtoMessage()    {}
func (*BreakfastPlayResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{13}
}

func (m *BreakfastPlayResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakfastPlayResponseMessage.Unmarshal(m, b)
}
func (m *BreakfastPlayResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakfastPlayResponseMessage.Marshal(b, m, deterministic)
}
func (m *BreakfastPlayResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakfastPlayResponseMessage.Merge(m, src)
}
func (m *BreakfastPlayResponseMessage) XXX_Size() int {
	return xxx_messageInfo_BreakfastPlayResponseMessage.Size(m)
}
func (m *BreakfastPlayResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakfastPlayResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BreakfastPlayResponseMessage proto.InternalMessageInfo

func (m *BreakfastPlayResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BreakfastPlayResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BreakfastPlayResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LunchPlayRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchPlayRequestMessage) Reset()         { *m = LunchPlayRequestMessage{} }
func (m *LunchPlayRequestMessage) String() string { return proto.CompactTextString(m) }
func (*LunchPlayRequestMessage) ProtoMessage()    {}
func (*LunchPlayRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{14}
}

func (m *LunchPlayRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchPlayRequestMessage.Unmarshal(m, b)
}
func (m *LunchPlayRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchPlayRequestMessage.Marshal(b, m, deterministic)
}
func (m *LunchPlayRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchPlayRequestMessage.Merge(m, src)
}
func (m *LunchPlayRequestMessage) XXX_Size() int {
	return xxx_messageInfo_LunchPlayRequestMessage.Size(m)
}
func (m *LunchPlayRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchPlayRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchPlayRequestMessage proto.InternalMessageInfo

func (m *LunchPlayRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//
//午餐前活动应答结构体
type LunchPlayResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunchPlayResponseMessage) Reset()         { *m = LunchPlayResponseMessage{} }
func (m *LunchPlayResponseMessage) String() string { return proto.CompactTextString(m) }
func (*LunchPlayResponseMessage) ProtoMessage()    {}
func (*LunchPlayResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{15}
}

func (m *LunchPlayResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunchPlayResponseMessage.Unmarshal(m, b)
}
func (m *LunchPlayResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunchPlayResponseMessage.Marshal(b, m, deterministic)
}
func (m *LunchPlayResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunchPlayResponseMessage.Merge(m, src)
}
func (m *LunchPlayResponseMessage) XXX_Size() int {
	return xxx_messageInfo_LunchPlayResponseMessage.Size(m)
}
func (m *LunchPlayResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LunchPlayResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LunchPlayResponseMessage proto.InternalMessageInfo

func (m *LunchPlayResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LunchPlayResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LunchPlayResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DinnerPlayRequestMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerPlayRequestMessage) Reset()         { *m = DinnerPlayRequestMessage{} }
func (m *DinnerPlayRequestMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerPlayRequestMessage) ProtoMessage()    {}
func (*DinnerPlayRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{16}
}

func (m *DinnerPlayRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerPlayRequestMessage.Unmarshal(m, b)
}
func (m *DinnerPlayRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerPlayRequestMessage.Marshal(b, m, deterministic)
}
func (m *DinnerPlayRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerPlayRequestMessage.Merge(m, src)
}
func (m *DinnerPlayRequestMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerPlayRequestMessage.Size(m)
}
func (m *DinnerPlayRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerPlayRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerPlayRequestMessage proto.InternalMessageInfo

func (m *DinnerPlayRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DinnerPlayResponseMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DinnerPlayResponseMessage) Reset()         { *m = DinnerPlayResponseMessage{} }
func (m *DinnerPlayResponseMessage) String() string { return proto.CompactTextString(m) }
func (*DinnerPlayResponseMessage) ProtoMessage()    {}
func (*DinnerPlayResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd7cfea030ce2b7, []int{17}
}

func (m *DinnerPlayResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DinnerPlayResponseMessage.Unmarshal(m, b)
}
func (m *DinnerPlayResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DinnerPlayResponseMessage.Marshal(b, m, deterministic)
}
func (m *DinnerPlayResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DinnerPlayResponseMessage.Merge(m, src)
}
func (m *DinnerPlayResponseMessage) XXX_Size() int {
	return xxx_messageInfo_DinnerPlayResponseMessage.Size(m)
}
func (m *DinnerPlayResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DinnerPlayResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DinnerPlayResponseMessage proto.InternalMessageInfo

func (m *DinnerPlayResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DinnerPlayResponseMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DinnerPlayResponseMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*BreakfastEatRequestMessage)(nil), "greetercenter.BreakfastEatRequestMessage")
	proto.RegisterType((*BreakfastEatResponseMessage)(nil), "greetercenter.BreakfastEatResponseMessage")
	proto.RegisterType((*LunchEatRequestMessage)(nil), "greetercenter.LunchEatRequestMessage")
	proto.RegisterType((*LunchEatResponseMessage)(nil), "greetercenter.LunchEatResponseMessage")
	proto.RegisterType((*DinnerEatRequestMessage)(nil), "greetercenter.DinnerEatRequestMessage")
	proto.RegisterType((*DinnerEatResponseMessage)(nil), "greetercenter.DinnerEatResponseMessage")
	proto.RegisterType((*BreakfastDrinkRequestMessage)(nil), "greetercenter.BreakfastDrinkRequestMessage")
	proto.RegisterType((*BreakfastDrinkResponseMessage)(nil), "greetercenter.BreakfastDrinkResponseMessage")
	proto.RegisterType((*LunchDrinkRequestMessage)(nil), "greetercenter.LunchDrinkRequestMessage")
	proto.RegisterType((*LunchDrinkResponseMessage)(nil), "greetercenter.LunchDrinkResponseMessage")
	proto.RegisterType((*DinnerDrinkRequestMessage)(nil), "greetercenter.DinnerDrinkRequestMessage")
	proto.RegisterType((*DinnerDrinkResponseMessage)(nil), "greetercenter.DinnerDrinkResponseMessage")
	proto.RegisterType((*BreakfastPlayRequestMessage)(nil), "greetercenter.BreakfastPlayRequestMessage")
	proto.RegisterType((*BreakfastPlayResponseMessage)(nil), "greetercenter.BreakfastPlayResponseMessage")
	proto.RegisterType((*LunchPlayRequestMessage)(nil), "greetercenter.LunchPlayRequestMessage")
	proto.RegisterType((*LunchPlayResponseMessage)(nil), "greetercenter.LunchPlayResponseMessage")
	proto.RegisterType((*DinnerPlayRequestMessage)(nil), "greetercenter.DinnerPlayRequestMessage")
	proto.RegisterType((*DinnerPlayResponseMessage)(nil), "greetercenter.DinnerPlayResponseMessage")
}

func init() { proto.RegisterFile("greetercenter/greetercenter.proto", fileDescriptor_5bd7cfea030ce2b7) }

var fileDescriptor_5bd7cfea030ce2b7 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x8b, 0x81, 0xaa, 0x4c, 0x4b, 0x55, 0xcd, 0xa1, 0x18, 0xb7, 0x95, 0xa8, 0xa5, 0x16,
	0x53, 0xa8, 0x69, 0xe9, 0x1b, 0x54, 0x70, 0x6b, 0xa5, 0x8a, 0x42, 0x9b, 0x28, 0x52, 0xa4, 0x0d,
	0x6c, 0x1c, 0x42, 0xb0, 0x89, 0xbd, 0x1c, 0xf2, 0x4c, 0x39, 0xe7, 0x9c, 0x57, 0x8b, 0x6c, 0x30,
	0x78, 0x37, 0x6b, 0x67, 0x0f, 0x7b, 0x5b, 0x56, 0xdf, 0xec, 0xfc, 0x98, 0x3f, 0x9f, 0x0c, 0x1f,
	0xbd, 0x90, 0x52, 0x46, 0xc3, 0x19, 0xf5, 0x19, 0x0d, 0xfb, 0xdc, 0x2f, 0x77, 0x1d, 0x06, 0x2c,
	0xc0, 0x3a, 0x77, 0x69, 0x7f, 0x03, 0xeb, 0x67, 0x48, 0xc9, 0xf2, 0x9c, 0x44, 0x6c, 0x44, 0xd8,
	0x98, 0x5e, 0x6f, 0x68, 0xc4, 0x7e, 0xd3, 0x28, 0x22, 0x1e, 0x45, 0x84, 0x8a, 0x4f, 0x56, 0xd4,
	0x2c, 0xb5, 0x4a, 0x4e, 0x6d, 0x9c, 0x9c, 0xed, 0xff, 0xf0, 0x8e, 0x8f, 0x88, 0xd6, 0x81, 0x1f,
	0xd1, 0x34, 0xe4, 0x0d, 0x94, 0x57, 0x91, 0xb7, 0x8b, 0x88, 0x8f, 0xf1, 0x23, 0xb3, 0x60, 0x4e,
	0x4d, 0xa3, 0x55, 0x72, 0xaa, 0xe3, 0xe4, 0x1c, 0xdf, 0xcd, 0x09, 0x23, 0x66, 0x79, 0xfb, 0x70,
	0x7c, 0xb6, 0x7b, 0xf0, 0xf6, 0xd7, 0xc6, 0x9f, 0x5d, 0xa8, 0x61, 0xfc, 0x85, 0xc6, 0x41, 0xad,
	0x0b, 0xe1, 0x2b, 0x34, 0x86, 0x0b, 0xdf, 0xa7, 0xa1, 0x1a, 0xc3, 0x04, 0xcc, 0x8c, 0x5c, 0x17,
	0xc4, 0x00, 0xde, 0xef, 0x0b, 0x3c, 0x0c, 0x17, 0xfe, 0x52, 0x81, 0xe4, 0x18, 0x3e, 0x88, 0x31,
	0xba, 0x70, 0x5c, 0x30, 0x93, 0x42, 0xab, 0xa2, 0x4c, 0xa1, 0x99, 0xd5, 0xeb, 0xc2, 0xe8, 0x43,
	0x73, 0x5b, 0x6b, 0x55, 0x8e, 0x7f, 0x60, 0x71, 0x01, 0xba, 0x40, 0xbe, 0x67, 0xe6, 0xff, 0xcf,
	0x15, 0xb9, 0x51, 0x40, 0x39, 0xca, 0x74, 0x74, 0x1b, 0xa2, 0x71, 0x60, 0x93, 0x62, 0x2b, 0x82,
	0x4c, 0x76, 0xbd, 0xd4, 0x0b, 0xe1, 0xa6, 0x6b, 0xa0, 0x48, 0x31, 0x4d, 0x5b, 0xa9, 0x15, 0x63,
	0x70, 0x6b, 0x40, 0x79, 0x44, 0x18, 0x7a, 0xf0, 0x2a, 0x6b, 0x50, 0xd8, 0x71, 0x79, 0x1f, 0xcc,
	0xf7, 0x3b, 0xeb, 0x4b, 0xa1, 0x94, 0x03, 0xb5, 0x9f, 0xe1, 0x09, 0xbc, 0x48, 0x2d, 0x08, 0x3f,
	0x09, 0x91, 0x72, 0x27, 0xb3, 0x3e, 0xe7, 0xca, 0xc4, 0xc7, 0x4f, 0xa1, 0xb6, 0xf7, 0x16, 0x14,
	0xc3, 0x72, 0x4c, 0xca, 0x6a, 0xe7, 0xeb, 0x84, 0xf7, 0x07, 0xf7, 0x06, 0x54, 0x93, 0xcd, 0xc0,
	0x15, 0xbc, 0xe6, 0xbd, 0x03, 0xbb, 0x79, 0x65, 0x90, 0xec, 0x9e, 0xd5, 0x7b, 0x42, 0x2c, 0xfe,
	0x31, 0x02, 0x70, 0xf0, 0x07, 0x6c, 0xcb, 0x0a, 0x22, 0x4b, 0xe3, 0x14, 0x08, 0xc5, 0x14, 0x73,
	0x78, 0x99, 0x59, 0x7d, 0x74, 0xa4, 0x55, 0x91, 0x25, 0xe9, 0x14, 0x29, 0xc5, 0x0a, 0xde, 0x19,
	0x50, 0x89, 0x27, 0x18, 0x2f, 0xa1, 0xce, 0xad, 0x37, 0xe6, 0x8e, 0xd1, 0xe3, 0x05, 0xb1, 0xba,
	0xc5, 0x5a, 0xc9, 0x58, 0xec, 0x37, 0x18, 0xa5, 0xd3, 0x24, 0xc9, 0xd1, 0xce, 0xd7, 0x49, 0xba,
	0x73, 0xd8, 0x4d, 0x94, 0xcf, 0x93, 0x24, 0x83, 0x53, 0x20, 0x14, 0x52, 0x9c, 0x3d, 0x4f, 0x3e,
	0x44, 0x7e, 0x3c, 0x04, 0x00, 0x00, 0xff, 0xff, 0x85, 0xa5, 0xab, 0xea, 0xad, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EatClient is the client API for Eat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EatClient interface {
	BreakfastEat(ctx context.Context, in *BreakfastEatRequestMessage, opts ...grpc.CallOption) (*BreakfastEatResponseMessage, error)
	LunchEat(ctx context.Context, in *LunchEatRequestMessage, opts ...grpc.CallOption) (*LunchEatResponseMessage, error)
	DinnerEat(ctx context.Context, in *DinnerEatRequestMessage, opts ...grpc.CallOption) (*DinnerEatResponseMessage, error)
}

type eatClient struct {
	cc *grpc.ClientConn
}

func NewEatClient(cc *grpc.ClientConn) EatClient {
	return &eatClient{cc}
}

func (c *eatClient) BreakfastEat(ctx context.Context, in *BreakfastEatRequestMessage, opts ...grpc.CallOption) (*BreakfastEatResponseMessage, error) {
	out := new(BreakfastEatResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Eat/BreakfastEat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eatClient) LunchEat(ctx context.Context, in *LunchEatRequestMessage, opts ...grpc.CallOption) (*LunchEatResponseMessage, error) {
	out := new(LunchEatResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Eat/LunchEat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eatClient) DinnerEat(ctx context.Context, in *DinnerEatRequestMessage, opts ...grpc.CallOption) (*DinnerEatResponseMessage, error) {
	out := new(DinnerEatResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Eat/DinnerEat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EatServer is the server API for Eat service.
type EatServer interface {
	BreakfastEat(context.Context, *BreakfastEatRequestMessage) (*BreakfastEatResponseMessage, error)
	LunchEat(context.Context, *LunchEatRequestMessage) (*LunchEatResponseMessage, error)
	DinnerEat(context.Context, *DinnerEatRequestMessage) (*DinnerEatResponseMessage, error)
}

// UnimplementedEatServer can be embedded to have forward compatible implementations.
type UnimplementedEatServer struct {
}

func (*UnimplementedEatServer) BreakfastEat(ctx context.Context, req *BreakfastEatRequestMessage) (*BreakfastEatResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BreakfastEat not implemented")
}
func (*UnimplementedEatServer) LunchEat(ctx context.Context, req *LunchEatRequestMessage) (*LunchEatResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LunchEat not implemented")
}
func (*UnimplementedEatServer) DinnerEat(ctx context.Context, req *DinnerEatRequestMessage) (*DinnerEatResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DinnerEat not implemented")
}

func RegisterEatServer(s *grpc.Server, srv EatServer) {
	s.RegisterService(&_Eat_serviceDesc, srv)
}

func _Eat_BreakfastEat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreakfastEatRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EatServer).BreakfastEat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Eat/BreakfastEat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EatServer).BreakfastEat(ctx, req.(*BreakfastEatRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eat_LunchEat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LunchEatRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EatServer).LunchEat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Eat/LunchEat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EatServer).LunchEat(ctx, req.(*LunchEatRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eat_DinnerEat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DinnerEatRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EatServer).DinnerEat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Eat/DinnerEat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EatServer).DinnerEat(ctx, req.(*DinnerEatRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Eat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetercenter.Eat",
	HandlerType: (*EatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BreakfastEat",
			Handler:    _Eat_BreakfastEat_Handler,
		},
		{
			MethodName: "LunchEat",
			Handler:    _Eat_LunchEat_Handler,
		},
		{
			MethodName: "DinnerEat",
			Handler:    _Eat_DinnerEat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetercenter/greetercenter.proto",
}

// DrinkClient is the client API for Drink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrinkClient interface {
	BreakfastDrink(ctx context.Context, in *BreakfastDrinkRequestMessage, opts ...grpc.CallOption) (*BreakfastDrinkResponseMessage, error)
	LunchDrink(ctx context.Context, in *LunchDrinkRequestMessage, opts ...grpc.CallOption) (*LunchDrinkResponseMessage, error)
	DinnerDrink(ctx context.Context, in *DinnerDrinkRequestMessage, opts ...grpc.CallOption) (*DinnerDrinkResponseMessage, error)
}

type drinkClient struct {
	cc *grpc.ClientConn
}

func NewDrinkClient(cc *grpc.ClientConn) DrinkClient {
	return &drinkClient{cc}
}

func (c *drinkClient) BreakfastDrink(ctx context.Context, in *BreakfastDrinkRequestMessage, opts ...grpc.CallOption) (*BreakfastDrinkResponseMessage, error) {
	out := new(BreakfastDrinkResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Drink/BreakfastDrink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkClient) LunchDrink(ctx context.Context, in *LunchDrinkRequestMessage, opts ...grpc.CallOption) (*LunchDrinkResponseMessage, error) {
	out := new(LunchDrinkResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Drink/LunchDrink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkClient) DinnerDrink(ctx context.Context, in *DinnerDrinkRequestMessage, opts ...grpc.CallOption) (*DinnerDrinkResponseMessage, error) {
	out := new(DinnerDrinkResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Drink/DinnerDrink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrinkServer is the server API for Drink service.
type DrinkServer interface {
	BreakfastDrink(context.Context, *BreakfastDrinkRequestMessage) (*BreakfastDrinkResponseMessage, error)
	LunchDrink(context.Context, *LunchDrinkRequestMessage) (*LunchDrinkResponseMessage, error)
	DinnerDrink(context.Context, *DinnerDrinkRequestMessage) (*DinnerDrinkResponseMessage, error)
}

// UnimplementedDrinkServer can be embedded to have forward compatible implementations.
type UnimplementedDrinkServer struct {
}

func (*UnimplementedDrinkServer) BreakfastDrink(ctx context.Context, req *BreakfastDrinkRequestMessage) (*BreakfastDrinkResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BreakfastDrink not implemented")
}
func (*UnimplementedDrinkServer) LunchDrink(ctx context.Context, req *LunchDrinkRequestMessage) (*LunchDrinkResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LunchDrink not implemented")
}
func (*UnimplementedDrinkServer) DinnerDrink(ctx context.Context, req *DinnerDrinkRequestMessage) (*DinnerDrinkResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DinnerDrink not implemented")
}

func RegisterDrinkServer(s *grpc.Server, srv DrinkServer) {
	s.RegisterService(&_Drink_serviceDesc, srv)
}

func _Drink_BreakfastDrink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreakfastDrinkRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkServer).BreakfastDrink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Drink/BreakfastDrink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkServer).BreakfastDrink(ctx, req.(*BreakfastDrinkRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drink_LunchDrink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LunchDrinkRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkServer).LunchDrink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Drink/LunchDrink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkServer).LunchDrink(ctx, req.(*LunchDrinkRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drink_DinnerDrink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DinnerDrinkRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkServer).DinnerDrink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Drink/DinnerDrink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkServer).DinnerDrink(ctx, req.(*DinnerDrinkRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Drink_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetercenter.Drink",
	HandlerType: (*DrinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BreakfastDrink",
			Handler:    _Drink_BreakfastDrink_Handler,
		},
		{
			MethodName: "LunchDrink",
			Handler:    _Drink_LunchDrink_Handler,
		},
		{
			MethodName: "DinnerDrink",
			Handler:    _Drink_DinnerDrink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetercenter/greetercenter.proto",
}

// PlayClient is the client API for Play service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayClient interface {
	BreakfastPlay(ctx context.Context, in *BreakfastPlayRequestMessage, opts ...grpc.CallOption) (*BreakfastPlayResponseMessage, error)
	LunchPlay(ctx context.Context, in *LunchPlayRequestMessage, opts ...grpc.CallOption) (*LunchPlayResponseMessage, error)
	DinnerPlay(ctx context.Context, in *DinnerPlayRequestMessage, opts ...grpc.CallOption) (*DinnerPlayResponseMessage, error)
}

type playClient struct {
	cc *grpc.ClientConn
}

func NewPlayClient(cc *grpc.ClientConn) PlayClient {
	return &playClient{cc}
}

func (c *playClient) BreakfastPlay(ctx context.Context, in *BreakfastPlayRequestMessage, opts ...grpc.CallOption) (*BreakfastPlayResponseMessage, error) {
	out := new(BreakfastPlayResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Play/BreakfastPlay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) LunchPlay(ctx context.Context, in *LunchPlayRequestMessage, opts ...grpc.CallOption) (*LunchPlayResponseMessage, error) {
	out := new(LunchPlayResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Play/LunchPlay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) DinnerPlay(ctx context.Context, in *DinnerPlayRequestMessage, opts ...grpc.CallOption) (*DinnerPlayResponseMessage, error) {
	out := new(DinnerPlayResponseMessage)
	err := c.cc.Invoke(ctx, "/greetercenter.Play/DinnerPlay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayServer is the server API for Play service.
type PlayServer interface {
	BreakfastPlay(context.Context, *BreakfastPlayRequestMessage) (*BreakfastPlayResponseMessage, error)
	LunchPlay(context.Context, *LunchPlayRequestMessage) (*LunchPlayResponseMessage, error)
	DinnerPlay(context.Context, *DinnerPlayRequestMessage) (*DinnerPlayResponseMessage, error)
}

// UnimplementedPlayServer can be embedded to have forward compatible implementations.
type UnimplementedPlayServer struct {
}

func (*UnimplementedPlayServer) BreakfastPlay(ctx context.Context, req *BreakfastPlayRequestMessage) (*BreakfastPlayResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BreakfastPlay not implemented")
}
func (*UnimplementedPlayServer) LunchPlay(ctx context.Context, req *LunchPlayRequestMessage) (*LunchPlayResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LunchPlay not implemented")
}
func (*UnimplementedPlayServer) DinnerPlay(ctx context.Context, req *DinnerPlayRequestMessage) (*DinnerPlayResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DinnerPlay not implemented")
}

func RegisterPlayServer(s *grpc.Server, srv PlayServer) {
	s.RegisterService(&_Play_serviceDesc, srv)
}

func _Play_BreakfastPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreakfastPlayRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).BreakfastPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Play/BreakfastPlay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).BreakfastPlay(ctx, req.(*BreakfastPlayRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_LunchPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LunchPlayRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).LunchPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Play/LunchPlay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).LunchPlay(ctx, req.(*LunchPlayRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_DinnerPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DinnerPlayRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).DinnerPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetercenter.Play/DinnerPlay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).DinnerPlay(ctx, req.(*DinnerPlayRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Play_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetercenter.Play",
	HandlerType: (*PlayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BreakfastPlay",
			Handler:    _Play_BreakfastPlay_Handler,
		},
		{
			MethodName: "LunchPlay",
			Handler:    _Play_LunchPlay_Handler,
		},
		{
			MethodName: "DinnerPlay",
			Handler:    _Play_DinnerPlay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetercenter/greetercenter.proto",
}
